DCN_ebnerd_large_x2_001_c76e9991:
    batch_norm: false
    batch_size: 8192
    dataset_id: ebnerd_large_x2_7ea969aa
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 10
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: impression_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [avgAUC, MRR, NDCG(k=5)]
    model: DCN
    model_root: ./checkpoints/
    monitor: avgAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCN_ebnerd_large_x2_002_a0857f88:
    batch_norm: false
    batch_size: 8192
    dataset_id: ebnerd_large_x2_7ea969aa
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 10
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: impression_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [avgAUC, MRR, NDCG(k=5)]
    model: DCN
    model_root: ./checkpoints/
    monitor: avgAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCN_ebnerd_large_x2_003_6c4df8b8:
    batch_norm: false
    batch_size: 8192
    dataset_id: ebnerd_large_x2_7ea969aa
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 10
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: impression_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [avgAUC, MRR, NDCG(k=5)]
    model: DCN
    model_root: ./checkpoints/
    monitor: avgAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
